











pub const MessageType = enum(u8) {

DATA_META = 0, DATA_META_GAME = 1, DATA_META_TIME = 2, DATA_META_OBS = 3, DATA_META_WIDGETS = 4, DATA_GAMES = 5, DATA_GAME = 6, DATA_GAMEACTIONS = 7, DATA_GAMEACTION = 8, DATA_FORMATS = 9, DATA_FORMAT = 10, DATA_TEAMS = 11, DATA_TEAM = 12, DATA_GROUPS = 13, DATA_GROUP = 14, DATA_IM_BOSS = 15, DATA_TIMESTAMP = 16, DATA_JSON = 17, IM_THE_BOSS = 18, PLS_SEND_META = 19, PLS_SEND_META_GAME = 20, PLS_SEND_META_TIME = 21, PLS_SEND_META_OBS = 22, PLS_SEND_META_WIDGETS = 23, PLS_SEND_GAMES = 24, PLS_SEND_GAME = 25, PLS_SEND_GAMEACTIONS = 26, PLS_SEND_GAMEACTION = 27, PLS_SEND_FORMATS = 28, PLS_SEND_FORMAT = 29, PLS_SEND_TEAMS = 30, PLS_SEND_TEAM = 31, PLS_SEND_GROUPS = 32, PLS_SEND_GROUP = 33, PLS_SEND_IM_BOSS = 34, PLS_SEND_TIMESTAMP = 35, PLS_SEND_JSON
 = 36,
};



