#!/bin/sh
set -e # quit on first command failure

case $1 in
	"windows-init")
		pakt -S mingw-w64-gcc nsis llvm +tmp
		curl -Lo nsis-3.zip \
			https://github.com/tauri-apps/binary-releases/releases/download/nsis-3/nsis-3.zip
		unzip nsis-3.zip
		sudo mkdir -p /usr/share/nsis/Stubs /usr/share/nsis/Plugins
		sudo cp nsis-3.08/Stubs/* /usr/share/nsis/Stubs/
		sudo cp -r nsis-3.08/Plugins/** /usr/share/nsis/Plugins/

		rustup target add x86_64-pc-windows-msvc
		cargo install --locked cargo-xwin
		;;
	"windows-build")
		bun tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
		;;
	"windows-run")
        wine src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/tauri-rentnerend_0.1.0_x64-setup.exe
		;;
	"windows-deinit")
		pakt -Rcnsu mingw-w64-gcc nsis llvm ++
		sudo rm -rfv nsis-3.zip nsis-3.08 /usr/share/nsis
		rustup target remove x86_64-pc-windows-msvc
		cargo uninstall cargo-xwin
		;;
	*)
		echo "Usage: $0 (windows-init|windows-build|windows-run|windows-deinit)"
		;;
esac
