




	





enum MessageType {
	
DATA_WIDGET_SCOREBOARD_ON(0), DATA_WIDGET_GAMEPLAN_ON(1), DATA_WIDGET_LIVETABLE_ON(2), DATA_WIDGET_GAMESTART_ON(3), DATA_WIDGET_AD_ON(4), DATA_OBS_STREAM_ON(5), DATA_OBS_REPLAY_ON(6), DATA_SIDES_SWITCHED(7), DATA_GAME(8), DATA_GAME_ACTION(9), DATA_GAMEINDEX(10), DATA_GAMEPART(11), DATA_PAUSE_ON(12), DATA_TIME(13), DATA_GAMESCOUNT(14), GAME_ACTION_DELETE(15), IM_THE_BOSS(16), DATA_IM_BOSS(17), DATA_TIMESTAMP(18), PLS_SEND_TIMESTAMP(19), PLS_SEND_IM_BOSS(20), PLS_SEND_WIDGET_SCOREBOARD_ON(21), PLS_SEND_WIDGET_GAMEPLAN_ON(22), PLS_SEND_WIDGET_LIVETABLE_ON(23), PLS_SEND_WIDGET_GAMESTART_ON(24), PLS_SEND_WIDGET_AD_ON(25), PLS_SEND_OBS_STREAM_ON(26), PLS_SEND_OBS_REPLAY_ON(27), PLS_SEND_SIDES_SWITCHED(28), PLS_SEND_GAME(29), PLS_SEND_GAME_ACTION(30), PLS_SEND_GAMEINDEX(31), PLS_SEND_GAMEPART(32), PLS_SEND_IS_PAUSE(33), PLS_SEND_TIME(34), PLS_SEND_GAMESCOUNT(35), PLS_SEND_JSON
(36), 
	DATA_JSON(123);

	final int value;
	const MessageType(this.value);
}

